version: '3.6'

services:
  nginx:
    build:
      dockerfile: .docker/nginx/Dockerfile
      context: .
    ports:
      - "8080:8080/tcp"
    user: 1000:1000
    volumes:
      - .docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    restart: always

  php-fpm:
      build:
        dockerfile: .docker/php-fpm/Dockerfile
        context: .
      volumes:
        - ./:/var/www/html
        - vendors:/var/www/html/vendor
      tmpfs:
        - /var/www/html/var
      environment:
        - APP_ENV=dev
  mongodb:
    image: mongo:4.2.22
    environment:
      MONGO_INITDB_ROOT_USERNAME: symfony
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  db-data:
  vendors: