version: '3.6'

services:
  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - .docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    restart: always

  php-fpm:
      build:
        context: .
      volumes:
        - ./:/var/www/html
      tmpfs:
        - /var/www/html/var
      environment:
        - APP_ENV=dev
  mongodb:
    image: mongo:4.2.22
    environment:
      MONGO_INITDB_ROOT_USERNAME: symfony
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  db-data:
