version: '3.6'

services:
  nginx:
    user: 1000:1000
    volumes:
      - public:/var/www/html/public
  php-fpm:
    build:
        dockerfile: .docker/php-fpm/Dockerfile-prod
        context: .
    volumes:
      - public:/public/

volumes:
  public: