# https://help.github.com/en/actions
name: Dockerize
on:
  release:
    types: [published]

env: # Environment variables
  APP_ENV: prod
  GH_TOKEN: ${{ secrets.GH_PERSONAL_TOKEN }}
jobs:
  docker_build:
    name: Build Docker image
    # https://hub.docker.com/_/ubuntu/
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@master
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          registry: ${{ steps.login-ecr.outputs.registry }}
          image: back
          cache: true
          tag: ${{github.ref_name}}
          build_file: Dockerfile-apache
          username: ${{ steps.login-ecr.outputs.docker_username }}
          password: ${{ steps.login-ecr.outputs.docker_password }}

